# Generated by Django 3.2.5 on 2021-07-31 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='cli_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud_app.department'),
            preserve_default=False,
        ),
    ]
