# Generated by Django 3.2.5 on 2021-07-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_clientinfo_cli_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='client_mode',
            field=models.CharField(choices=[('FULLTIME', 'Full time'), ('OUTSOURCING', 'Out Sourcing'), ('PARTTIME', 'Parttime')], default='FULLTIME', max_length=50),
        ),
    ]
