# Generated by Django 3.2.5 on 2021-07-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_clientinfo_client_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinfo',
            name='client_mode',
        ),
    ]
