# Generated by Django 3.2.5 on 2021-07-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0004_remove_clientinfo_client_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website Address'),
        ),
    ]
