# Generated by Django 3.2.5 on 2021-07-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0005_clientinfo_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='client_mode',
            field=models.CharField(choices=[('FULLTIME', 'Fulltime'), ('PARTTIME', 'Parttime')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
