# Generated by Django 3.2.5 on 2021-08-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0006_clientinfo_client_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/uploads'),
        ),
    ]
