# Generated by Django 3.2.5 on 2021-08-07 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0009_alter_clientinfo_client_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('website', models.URLField(blank=True, verbose_name='Website Address')),
                ('mode', models.CharField(choices=[('FULLTIME', 'Fulltime'), ('PARTTIME', 'Parttime'), ('OUTSOURCING', 'Outsourcing')], max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='client_images/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_app.department')),
            ],
        ),
        migrations.DeleteModel(
            name='ClientInfo',
        ),
    ]
