# Generated by Django 3.2.5 on 2021-08-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0010_auto_20210807_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='employee_images/'),
        ),
    ]
